spring:
  datasource:
    url: jdbc:mysql://localhost/DBgerenciaCafe?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: marcelo
    password: santosOl1ve1r@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
